# Generated by Django 2.1.4 on 2018-12-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20181216_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identification_photo',
            field=models.ImageField(upload_to='image_uploads/%Y/%m/%d/'),
        ),
    ]
